package com.surzhykov.navsymphony.choreographer.common

/**
 * Represents the entity that initiated the intent.
 *
 * This enum is used to identify the source or origin of an intent, helping to distinguish between
 * intents generated by the user, an internal middleware component, or the system itself.
 *
 *  - USER: Indicates that the intent was triggered by direct user interaction (e.g., clicking a
 *  button, typing a command).
 *  - MIDDLEWARE: Indicates that the intent was generated by one of middleware active object component
 *  - SYSTEM: Indicates that the intent was initiated by the underlying system or operating
 *  environment (e.g., a system event, a scheduled task, user interaction).
 */
interface IntentSender {
    data object User : IntentSender
    data object System : IntentSender
}